'use client';
import {useEffect,useMemo,useState} from 'react';
import AppShell from './AppShell';
import {api,API} from '../lib/api';
import AnalysisResult from './AnalysisResult';

type AIModule='llm'|'rag'|'agent'|'redteam';
const CONFIG: Record<AIModule,{title:string;button:string;family:string;description:string}>={
  llm:{title:'LLM Security',button:'Start LLM Security Assessment',family:'ai',description:'Assess prompt-injection, disclosure, output handling and model-boundary risks with bounded evidence-first campaigns.'},
  rag:{title:'RAG Security',button:'Start RAG Security Assessment',family:'rag',description:'Assess retrieval authorization, indirect injection, tenant isolation and knowledge-boundary weaknesses.'},
  agent:{title:'Agent / MCP Security',button:'Start Agent Security Assessment',family:'agent',description:'Assess tool permissions, excessive agency, identity boundaries and MCP configuration risk.'},
  redteam:{title:'AI Red Team',button:'Start Adaptive Red Team Campaign',family:'ai',description:'Run bounded multi-turn adaptive security campaigns and track evidence and retest state.'}
};
export default function AIModulePage({type}:{type:AIModule}){
 const cfg=CONFIG[type];
 const [url,setUrl]=useState(''); const [headers,setHeaders]=useState(''); const [provider,setProvider]=useState('generic-json');
 const [busy,setBusy]=useState(false); const [scanId,setScanId]=useState<number|null>(null); const [scan,setScan]=useState<any>(null); const [logs,setLogs]=useState<any[]>([]); const [findings,setFindings]=useState<any[]>([]); const [err,setErr]=useState('');
 const [mcp,setMcp]=useState('{\n  "servers": []\n}');
 const parseHeaders=useMemo(()=>{const out:Record<string,string>={}; for(const line of headers.split(/\r?\n/)){const i=line.indexOf(':'); if(i>0){out[line.slice(0,i).trim()]=line.slice(i+1).trim();}} return out;},[headers]);
 useEffect(()=>{if(!scanId)return; let stopped=false; const poll=async()=>{try{const [s,l,f]=await Promise.all([api(`/api/scans/${scanId}`),api(`/api/scans/${scanId}/logs`),api(`/api/console/findings?scan_id=${scanId}`)]); if(!stopped){setScan(s);setLogs(l);setFindings(f);} return ['completed','failed'].includes(s.status);}catch(e){if(!stopped)setErr(String(e)); return false;}}; poll(); const timer=setInterval(async()=>{if(await poll())clearInterval(timer)},900); return()=>{stopped=true;clearInterval(timer)};},[scanId]);
 async function run(){setBusy(true);setErr('');setFindings([]);try{const r=await api('/api/console/ai/start',{method:'POST',body:JSON.stringify({kind:type,target_url:url,provider,headers:parseHeaders,max_turns:4,query_field:'query',message_field:'message'})});setScanId(r.scan_id);}catch(e:any){setErr(e.message||'Unable to start assessment.');}finally{setBusy(false)}}
 async function analyzeMcp(){setBusy(true);setErr('');try{const parsed=JSON.parse(mcp);const d=await api('/api/console/ai/mcp',{method:'POST',body:JSON.stringify({config:parsed})});setScanId(d.scan_id);const [s,f,l]=await Promise.all([api(`/api/scans/${d.scan_id}`),api(`/api/console/findings?scan_id=${d.scan_id}`),api(`/api/scans/${d.scan_id}/logs`)]);setScan(s);setFindings(f);setLogs(l);}catch(e:any){setErr(e.message||'Invalid MCP configuration or analysis failed.')}finally{setBusy(false)}}
 return <AppShell><div className="page-stack">
  <section className="hero-strip"><div><span className="eyebrow">AI SECURITY / {type.toUpperCase()}</span><h2>{cfg.title}</h2><p>{cfg.description}</p></div>{scanId&&<span className="mode-chip">ASSESSMENT #{scanId}</span>}</section>
  {type==='agent' ? <div className="tool-tabs"><button className="tab active">Agent Security</button><button className="tab" onClick={analyzeMcp}>MCP Analyzer</button></div>:null}
  {type==='agent' ? <section className="panel ai-dual-panel"><div className="module-card"><span className="card-kicker">AGENT</span><h3>Agent Security Assessment</h3><div className="form-grid two"><Field label="Authorized Agent URL"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://authorized-agent.example/api/chat"/></Field><Field label="Provider"><select value={provider} onChange={e=>setProvider(e.target.value)}><option>generic-json</option><option>openai-compatible</option><option>anthropic-compatible</option><option>gemini-compatible</option></select></Field></div><Field label="Request Headers (optional)"><textarea value={headers} onChange={e=>setHeaders(e.target.value)} placeholder="Authorization: Bearer …"/></Field><button className="btn primary" disabled={busy||!url} onClick={run}>{busy?'Starting…':'Start Agent Security Assessment'}</button></div><div className="module-card"><span className="card-kicker">MCP</span><h3>MCP Configuration Analysis</h3><Field label="MCP Configuration JSON"><textarea value={mcp} onChange={e=>setMcp(e.target.value)} /></Field><button className="btn purple-bg" disabled={busy||!mcp} onClick={analyzeMcp}>{busy?'Analyzing…':'Analyze MCP Configuration'}</button></div></section>:
  <section className="panel"><div className="form-grid two"><Field label="Authorized Target URL"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://authorized-ai.example/api/chat"/></Field><Field label="Provider"><select value={provider} onChange={e=>setProvider(e.target.value)}><option>generic-json</option><option>openai-compatible</option><option>anthropic-compatible</option><option>gemini-compatible</option></select></Field></div><Field label="Request Headers (optional)"><textarea value={headers} onChange={e=>setHeaders(e.target.value)} placeholder="Authorization: Bearer …"/></Field>{err&&<div className="notice error">{err}</div>}<button className="btn primary" onClick={run} disabled={busy||!url}>{busy?'Starting…':cfg.button}</button></section>}
  {err&&type==='agent'&&<div className="notice error">{err}</div>}
  {scanId&&<section className="panel live-panel"><div className="panel-head"><div><span className="eyebrow">LIVE ASSESSMENT</span><h3>{scan?.assessment_name||cfg.title}</h3><p className="muted">{scan?.target_url_snapshot||url}</p></div><div className="progress-block"><b>{scan?.progress||0}%</b><div className="progress-track"><span style={{width:`${scan?.progress||0}%`}}/></div><span className="mode-chip">{scan?.status||'queued'}</span></div></div><div className="log-console">{logs.length?logs.map((l:any)=><div className="log-line" key={l.id}><span className="log-time">{new Date(l.timestamp).toLocaleTimeString()}</span><span className={`log-level ${String(l.level).toLowerCase()}`}>{l.level}</span><span>{l.message}</span></div>):<div className="empty">Waiting for assessment logs…</div>}</div></section>}
  {scan?.status==='completed'&&<AnalysisResult result={{status:scan.status,target_url:scan.target_url_snapshot,findings,observations:logs}} scannerFamily={cfg.family} title={`${cfg.title} Results`}/>} 
 </div></AppShell>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
