'use client';
import {useState} from 'react';
import AppShell from './AppShell';
import {api} from '../lib/api';

export default function CSPAnalyzer(){
 const [tab,setTab]=useState<'url'|'directives'>('url'); const [url,setUrl]=useState(''); const [directives,setDirectives]=useState(''); const [res,setRes]=useState<any>(null); const [busy,setBusy]=useState(false); const [err,setErr]=useState('');
 async function run(){setBusy(true);setErr('');setRes(null);try{const d=tab==='url'?await api('/api/console/csp',{method:'POST',body:JSON.stringify({target_url:url})}):await api('/api/console/csp/directives',{method:'POST',body:JSON.stringify({content:directives})});setRes(d);}catch(e:any){setErr(e.message||'CSP analysis failed.')}finally{setBusy(false)}}
 const findings=Array.isArray(res?.findings)?res.findings:[];
 return <AppShell><div className="page-stack">
  <section className="hero-strip"><div><span className="eyebrow">WEB SECURITY / CSP</span><h2>CSP Analyzer</h2><p>Separate target-response inspection from standalone CSP directive review. Every finding includes severity, rationale, impact and remediation.</p></div><span className="mode-chip">HTTP HEADER ANALYSIS</span></section>
  <div className="tool-tabs"><button className={tab==='url'?'tab active':'tab'} onClick={()=>{setTab('url');setRes(null)}}>Target URL Scan</button><button className={tab==='directives'?'tab active':'tab'} onClick={()=>{setTab('directives');setRes(null)}}>Directive Analysis</button></div>
  <section className="panel"><label className="field"><span>{tab==='url'?'Target URL':'CSP Directives'}</span>{tab==='url'?<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com"/>:<textarea value={directives} onChange={e=>setDirectives(e.target.value)} placeholder="default-src 'self'; script-src 'self' 'nonce-…'; object-src 'none';"/>}</label>{err&&<div className="notice error">{err}</div>}<button className="btn primary" disabled={busy||!(tab==='url'?url:directives)} onClick={run}>{busy?'Analyzing…':tab==='url'?'Scan Target & Analyze CSP':'Analyze CSP Directives'}</button></section>
  {res&&<section className="panel result-panel"><div className="result-summary rich"><div><span>Analysis Target</span><strong>{tab==='url'?res.target_url||url:'Directive input'}</strong></div><div><span>HTTP Status</span><strong>{tab==='url'?(res.status_code||'—'):'N/A'}</strong></div><div><span>CSP Enforcement</span><strong>{res.present?'Present':'Missing'}</strong></div><div><span>Policy Score</span><strong>{res.score??'—'}</strong></div></div>
   {tab==='url'&&res.headers&&<details className="detail-block" open><summary><b>HTTP Response Headers</b></summary><div className="header-grid">{Object.entries(res.headers).map(([k,v]:any)=><div key={k}><span>{k}</span><code>{String(v)}</code></div>)}</div></details>}
   <div className="panel-head"><div><span className="eyebrow">DIRECTIVES</span><h3>Policy breakdown</h3></div></div><div className="directive-grid">{Object.entries(res.directives||{}).map(([k,v]:any)=><div key={k}><b>{k}</b><span>{Array.isArray(v)?v.join(' '):String(v)}</span></div>)}</div>
   <div className="finding-stack">{findings.map((f:any,i:number)=><article className="finding-detail" key={f.finding_key||i}><div className="finding-detail-head"><div><span className="finding-key">{f.finding_key||`CSP-${i+1}`}</span><b>{f.title||'CSP finding'}</b></div><span className={`sev ${f.severity||'info'}`}>{f.severity||'info'}</span></div><div className="finding-expanded"><p>{f.description||'No description supplied.'}</p><div className="finding-two"><div><small>Why this risk</small><p>{why(f.severity)}</p></div><div><small>Impact</small><p>{f.impact||'Weak policy design reduces browser-enforced defense-in-depth.'}</p></div></div><div className="detail-block"><b>Remediation</b><p>{f.remediation||'Tighten trust sources and prefer nonces/hashes over unsafe inline execution.'}</p></div></div></article>)}</div>
  </section>}
 </div></AppShell>
}
function why(s:string){return s==='high'?'The directive materially weakens CSP enforcement or creates a broad executable trust boundary.':s==='medium'?'The directive weakens a defense-in-depth control or broadens allowed origins.':s==='low'?'Hardening is reduced, but the condition is generally not sufficient for standalone exploitation.':'Informational posture or metadata.'}
