'use client';
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell'; import {api} from '../../lib/api'; import {useSearchParams} from 'next/navigation';
export default function WebSecurity({initialTab='new'}:{initialTab?:'new'|'auth'}){
 const params=useSearchParams(); const [tab,setTab]=useState<'new'|'auth'>(params.get('tab')==='auth'?'auth':initialTab); const [name,setName]=useState(''); const [url,setUrl]=useState(''); const [mode,setMode]=useState('balanced'); const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false); const [scanId,setScanId]=useState<number|null>(null); const [scan,setScan]=useState<any>(null); const [logs,setLogs]=useState<any[]>([]); const [err,setErr]=useState('');
 useEffect(()=>{if(!scanId)return; const t=setInterval(async()=>{try{const [s,l]=await Promise.all([api(`/api/scans/${scanId}`),api(`/api/scans/${scanId}/logs`)]);setScan(s);setLogs(l);if(['completed','failed'].includes(s.status))clearInterval(t)}catch{}},900);return()=>clearInterval(t)},[scanId]);
 async function start(){setBusy(true);setErr('');try{const r=tab==='new'?await api('/api/console/web/assessment',{method:'POST',body:JSON.stringify({assessment_name:name,target_url:url,mode})}):await api('/api/console/web/authenticated',{method:'POST',body:JSON.stringify({assessment_name:name,target_url:url,mode,username,password})});setScanId(r.scan_id);setPassword('')}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 return <AppShell><div className="page-stack"><section className="hero-strip"><div><span className="eyebrow">WEB SECURITY</span><h2>Deep Web Security Assessment</h2><p>Commercial-style assessment workflow with background execution and live capture logs.</p></div><div className="mode-chip">BROWSER + HTTP</div></section><div className="tool-tabs"><button className={tab==='new'?'tab active':'tab'} onClick={()=>setTab('new')}>New Assessment</button><button className={tab==='auth'?'tab active':'tab'} onClick={()=>setTab('auth')}>Authenticated Scan</button></div><section className="panel"><div className="form-grid three"><Field label="Assessment Name"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Production Web Security Assessment"/></Field><Field label="Target URL"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://target.example.com"/></Field><Field label="Mode"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="fast">Fast</option><option value="balanced">Balanced</option><option value="deep">Deep Scan</option></select></Field>{tab==='auth'&&<><Field label="Username"><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="authorized-user@example.com"/></Field><Field label="Password"><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Password"/></Field></>}</div>{err&&<div className="notice error">{err}</div>}<div className="action-row"><button className="btn primary" onClick={start} disabled={busy||!name||!url||(tab==='auth'&&(!username||!password))}>{busy?'Starting…':tab==='new'?'Start Scan':'Authenticate & Scan'}</button>{scanId&&<span className="assessment-running">Assessment #{scanId} {scan?.status?.toUpperCase()}</span>}</div></section>{scanId&&<section className="panel live-panel"><div className="panel-head"><div><span className="eyebrow">LIVE CAPTURE</span><h3>{scan?.assessment_name||name}</h3><p className="muted">{scan?.target_url||url}</p></div><div className="progress-block"><b>{scan?.progress||0}%</b><div className="progress-track"><span style={{width:`${scan?.progress||0}%`}}/></div></div></div><div className="log-console">{logs.length?logs.map(l=><div className="log-line" key={l.id}><span className="log-time">{new Date(l.timestamp).toLocaleTimeString()}</span><span className={`log-level ${l.level.toLowerCase()}`}>{l.level}</span><span>{l.message}</span></div>):<div className="empty">Waiting for scan logs…</div>}</div></section>}</div></AppShell>}
function Field({label,children}:{label:string;children:any}){return <label className="field"><span>{label}</span>{children}</label>}
